zm/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib import admin

from mapa.views import *
admin.autodiscover()

from django.contrib.sitemaps import Sitemap
from mapa.models import Poi

class MistaSitemap(Sitemap):
    def items(self):
        return Poi.viditelne.all()

sitemaps = {
        'mista': MistaSitemap
}

urlpatterns = patterns('',
    (r'^mapwidget/', include("mapwidget.urls")),
    (r'^$', mapa_view),
    (r'^misto/(\d+)/$', mapa_view),
    (r'^kml/([-\w]+)/$', kml_view),
    (r'^popup/(\d+)/$', popup_view),
    (r'^doplnit/(\d+)/$', 'mapa.views.addpoi_view'),
    (r'^doplnit/$', 'mapa.views.addpoi_view'),
    (r'^detail/(\d+)/', detail_view),
    (r'^vlastnosti/', vlastnosti_view),
    (r'^vrstvy/', vrstvy_view),
    (r'^znacky/', znacky_view),
    (r'^festival/(.*)', festival_view),
    (r'^search/([- \w]+)/$', search_view),
    (r'^admin/', include(admin.site.urls)),
    (r'^clanky/(.*)', static_view),
    # mobilni verze
    (r'^hledani/$', m_hledani),
    (r'^vypis/$', m_vypis),
    (r'^vypis/(\d+)/$', m_detail),
    # sitemap pro vyhledavace
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})

)

urlpatterns += staticfiles_urlpatterns()
    
if settings.DEBUG:
    urlpatterns += patterns('',
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes = True) \
      + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes = True) \
      + static('images', document_root=settings.MEDIA_ROOT + '/images', show_indexes = True)

comment/models.py
from django.db import models

from mapa.models import Poi


class Comment(models.Model):
    poi = models.ForeignKey(Poi)
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __unicode__(self):
        return u"%s (%s) ~%i %s" % (self.name, self.email, self.pk, self.content[:20])

mapa/models.py
# -*- coding: utf-8 -*-
import datetime

from django.contrib.gis.db import models
from django.utils.safestring import mark_safe
from django.core.cache import cache

from django.contrib.auth.models import User

class Status(models.Model):
    "Stavy zobrazeni konkretniho objektu, vrstvy apod."
    nazev   = models.CharField(max_length=255)                      # Nazev statutu
    desc    = models.TextField(null=True, blank=True)               # Description
    show    = models.BooleanField()                                 # Zobrazit uzivateli zvenci
    show_TU = models.BooleanField()                                 # Zobrazit editorovi mapy

    class Meta:
        verbose_name_plural = "Statuty"
    def __unicode__(self):
        return self.nazev
    

class Vrstva(models.Model):
    "Vrstvy, ktere se zobrazi v konkretni mape"
    nazev   = models.CharField(max_length=255)                      # Name of the layer
    slug    = models.SlugField(unique=True, verbose_name=u"název v URL")  # Vrstva v URL
    desc    = models.TextField(null=True, blank=True)               # Description
    status  = models.ForeignKey(Status)              # zobrazovaci status
    order   = models.PositiveIntegerField()
    remark  = models.TextField(null=True, blank=True, help_text=u"interni informace o objektu, ktere se nebudou zobrazovat")

    class Meta:
        verbose_name_plural = u"vrstvy"
        ordering = ['order']
    def __unicode__(self):
        return self.nazev

class Znacka(models.Model):
    "Mapove znacky vcetne definice zobrazeni"
    nazev   = models.CharField(max_length=255)   # Name of the mark
    
    # Relationships
    vrstva  = models.ForeignKey(Vrstva)              # Kazda znacka lezi prave v jedne vrstve
    status  = models.ForeignKey(Status)              # kvuli vypinani
    
    # icon: Neni zde, ale v tabulce znacky a vztahuje se k rozlicnym zobrazenim 
    # Pro zjednoduseni mame image "default_icon", ale to je jen nouzove reseni, 
    # ktere nesmi nahradit system znacek zavislych na zobrazeni, etc.
    
    # content 
    desc    = models.TextField(null=True, blank=True, help_text=u"podrobny popis znacky")
    remark  = models.TextField(null=True, blank=True, help_text=u"interni informace o objektu, ktere se nebudou zobrazovat")
    
    # Base icon and zoom dependent display range
    default_icon = models.ImageField(null=True, upload_to='ikony') # XXX: zrusit null=True
    mobile_icon = models.ImageField(null=True, upload_to='ikony_m') # XXX: zrusit null=True
    minzoom = models.PositiveIntegerField(default=1)
    maxzoom = models.PositiveIntegerField(default=10)
    
    class Meta:
        verbose_name_plural = "Znacky"
    def __unicode__(self):
        return self.nazev

class ViditelneManager(models.GeoManager):
    def get_query_set(self):
        return super(ViditelneManager, self).get_query_set().filter(status__show=True, znacka__status__show=True)

class Poi(models.Model):
    "Misto - bod v mape"
    author = models.ForeignKey(User, verbose_name="Autor")
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name="Posledni zmena")

    nazev   = models.CharField(max_length=255, verbose_name=u"název")   # Name of the location
    
    # Relationships
    znacka  = models.ForeignKey(Znacka, verbose_name=u"značka")          # "Znacky"   - misto ma prave jednu
    status  = models.ForeignKey(Status)          # "Statuty"  - misto ma prave jeden
    vlastnosti    = models.ManyToManyField('Vlastnost', blank=True, null=True)       # "Vlastnosti" - ma vice
    
    # "dulezitost" - modifikator minimalniho zoomu, ve kterem se misto zobrazuje. 
    dulezitost = models.SmallIntegerField(default=0, verbose_name=u"důležitost",
                 help_text=u"""Modifikátor minimalniho zoomu, ve kterém se místo zobrazuje (20+ bude vidět vždy). 
                               Cíl je mít výběr základních objektů viditelných ve velkých měřítcích
                               a zabránit přetížení mapy značkami v přehledce.
                               Lze použít pro placenou reklamu! ("Váš podnik bude vidět hned po otevření mapy")""")
    
    # Geographical intepretation
    geom    = models.PointField(verbose_name=u"poloha",srid=4326, help_text=u"Klikni na tužku s plusem a umisti bod na mapu")
    objects = models.GeoManager()
    
    # Own content (facultative)
    desc    = models.TextField(null=True, blank=True, verbose_name=u"popis", help_text=u"Text do buliny na mapě")
    desc_extra = models.TextField(null=True, blank=True, verbose_name=u"podrobný popis", help_text="Text do detailu místa (mimo bublinu)")
    url     = models.URLField(null=True, blank=True, help_text=u"Webový odkaz na stránku podniku apod.")
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name=u"adresa")
    remark  = models.TextField(null=True, blank=True, verbose_name=u"interní poznámka", help_text=u"Interní informace o objektu, které se nebudou zobrazovat")

    # 3 fotografie museji pro vetsinu ucelu stacit
    foto_thumb  = models.ImageField(null=True, blank=True, upload_to='foto', verbose_name=u"foto", help_text=u"Velikost max. 500x400px") # 150 x 100 px
#    foto2 = models.ImageField(null=True, blank=True, upload_to='foto') 
#    foto3 = models.ImageField(null=True, blank=True, upload_to='foto') 
    
    # zde se ulozi slugy vsech vlastnosti, aby se pri renederovani kml
    # nemusel delat db dotaz pro kazde Poi na jeho vlastnosti
    vlastnosti_cache = models.CharField(max_length=255, null=True, blank=True)
    
    viditelne = ViditelneManager()
    
    class Meta:
        verbose_name = "místo"
        verbose_name_plural = "místa"
    def __unicode__(self):
        return self.nazev
    def save_vlastnosti_cache(self):
        self.vlastnosti_cache = u",".join([v.slug for v in self.vlastnosti.filter(status__show=True)])
        self.save()
    def get_absolute_url(self):
        return "/misto/%i/" % self.id

    def save(self, *args, **kwargs):
        self.created_at = datetime.datetime.now()
        super(Poi, self).save(*args, **kwargs)

from django.db.models.signals import m2m_changed, post_save
def update_vlastnosti_cache(sender, instance, action, reverse, model, pk_set, **kwargs):
    "Aktualizace cache vlastnosti pri ulozeni Poi. Je treba jeste vyresit smazani Vlastnosti"
    if action == 'post_add':
        instance.save_vlastnosti_cache()
m2m_changed.connect(update_vlastnosti_cache, Poi.vlastnosti.through) 

def invalidate_cache(sender, instance, **kwargs):
    if sender in [Status, Vrstva, Znacka, Poi, Vlastnost, Staticpage]:
        cache.clear()
post_save.connect(invalidate_cache)
    

class Vlastnost(models.Model):
    "Vlastnosti mist"
    nazev   = models.CharField(max_length=255)   # Name of the property
    status  = models.ForeignKey(Status)          # "Statuty"  - tj. active/inactive. Mozny je i boolean "active"
    filtr   = models.BooleanField()              # Pouzit v levem menu, filtrovat???
    poradi  = models.PositiveIntegerField()
    # content 
    slug    = models.SlugField(unique=True, verbose_name="Slug")  # Popis tagu v URL
    desc    = models.TextField(null=True, blank=True) # podrobny popis vlastnosti
    remark  = models.TextField(null=True, blank=True, help_text=u"interni informace o objektu, ktere se nebudou zobrazovat")
    default_icon = models.ImageField(null=True, upload_to='ikony') # XXX: zrusit null=True
   
    class Meta:
        verbose_name_plural = u"vlastnosti"
	ordering = ['poradi']
    def __unicode__(self):
        return self.nazev

UPRESNENI_CHOICE = (
        ('novy', u'Nový'),
        ('reseno', u'V řešení'),
        ('vyreseno', u'Vyřešeno'),
        ('zamitnuto', u'Zamítnuto'),
)

class Upresneni(models.Model):
    """
    Tabulka pro uzivatelske doplnovani informaci do mapy. 
    Prozatim na proncipu rucniho prepisu udaju v adminu.
    Vyzchazi z POI, ale nekopiruje se do ni.
    Slouzi predevsim k doplneni informace k mistu. Nektera pole mohou byt proto nefunkncni.
    """
    misto  = models.ForeignKey(Poi, blank=True, null=True) # Odkaz na objekt, ktery chce opravit, muze byt prazdne.
    email  = models.EmailField(verbose_name=u"Váš e-mail (pro další komunikaci)", null=True)    # Prispevatel musi vyplnit email.
    status  = models.CharField(max_length=10,choices=UPRESNENI_CHOICE) 
    desc    = models.TextField(verbose_name=u"Popis (doplnění nebo oprava nebo popis nového místa, povinné pole)",null=True)
    url     = models.URLField(verbose_name=u"Odkaz, webové stránky místa (volitelné pole)",null=True, blank=True)  # Odkaz z vypisu - stranka podniku apod.
    address = models.CharField(verbose_name=u"Adresa místa, popis lokace (volitelné pole)",max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = u"upřesnění"
    def __unicode__(self):
        return u"%s - %s" % (self.misto, self.email)

    
class Staticpage(models.Model):
    "Tabulka statickeho obsahu webu"
    slug    = models.SlugField(unique=True, verbose_name="Slug")  # extenze v URL
    head    = models.TextField(verbose_name=u"Header section (additional css, js, etc.)",null=True, blank=True)
    title   = models.CharField(verbose_name=u"Titulek straky",max_length=255, null=True, blank=True)
    short   = models.TextField(verbose_name=u"Zkraceny html obsah (nahled)",null=True)
    content = models.TextField(verbose_name=u"Html obsah",null=True)
    
    def __unicode__(self):
        return self.title

zm/templates/addpoi.html
{% load static %}
{% load url from future %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
   
   <title>Doplneni</title>
  </head>
  <body class="static">
  <div class="content_left">
   {% if poi %}

       <h2>Doplnění informací o místě:<br>{{ poi }}</h2>

       <div class="vkladani_aktual" >
       <h4>Aktuální stav:</h4>
       
       <p style="font-weight:bold;"><img src="{{ poi.znacka.default_icon.url }}" title="{{ poi.znacka }}" class="poi_znacka"> {{ poi.znacka }}</p>

       <p class="titulek">Vlastnosti:</p>
       <ul class="misto_vlastnosti">
       {% for vl in poi.vlastnosti.all %}
            <li><img src="{{ vl.default_icon.url }}" title="{{ vl.desc }}">{{  vl.nazev }}</li>
       {% endfor %}
       </ul>    
  
       {% if poi.address %}
       <p class="titulek">Adresa:</p>
       <p>{{ poi.address|safe }}</p>
       {% endif %}
   
       {% if poi.url %}
       <p class="titulek">Odkaz:</p>
       <p><a href="{{ poi.url|safe }}" title="{{ poi.url|safe }}">{{ poi.url|safe }}</a></p>
       {% endif %}
   
       {% if poi.desc %}
       <p class="titulek">Popis:</p>
       <p>{{ poi.desc|safe }}</p>
       {% endif %}
    
       {% if poi.desc_extra %}
       <p>{{ poi.desc_extra|safe }}</p>
       {% endif %}

       {% if poi.foto_thumb %}
            <img src="{{ MEDIA_URL }}{{ poi.foto_thumb }}" title="{{ poi }}" class="foto_thumb_edit">
       {% else %}	    
            <div class="foto_thumb_edit" style="display:none;"></div>
       {% endif %}
       
       </div>

   
   
   {% else %}
       <div class="left">
       <h2>Navrhuji nové místo</h2>
       <p>Rád bych do Zelené mapy doplnil(a) následující místo...</p>
   {% endif %}


  {% if poi %}
  <div class="formt" style="width:250px; text-align:left;">
<form action="{% url 'mapa.views.addpoi_view' poi.id %}" method="post">
   {% else %}
<form action="{% url 'mapa.views.addpoi_view' %}" method="post">
   {% endif %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}:<br/>
            {{ field }}
        </div>
    {% endfor %}
<button><input type="submit" value="Odeslat" /></button>

</form>
</div>

{{ static_vkladani.content|safe }}

</div>
</div>

</body>
</html>

zm/templates/festival.html
{% load static %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
  {{ static.head  }}
  <title>{{ static.title }}</title>
  </head>
  <body class="static">
  <div class="content_left">
  
  <h1>{{ static.title }}</h1>
  {{ static.short|safe }}

  {% if wordpresscat %}
      {{ wordpresscat|safe }}
  {% endif %} 
  
  {{ static.content|safe }}
  
  {% if pois %}

  {% for poi in pois %}
       <h3><a href="/#detail={{ poi.id }}" target="_top">{{ poi }}</a>
       {% for vl in poi.vlastnosti.all %}
       {% if vl.status.show %}
       <img src="{{ vl.default_icon.url }}" title="{{ vl.nazev }}">
       {% endif %}    
       {% endfor %}
       </h3>

       {% if poi.desc %}
       <p>{{ poi.desc|safe }}</p>
       {% else %}
       <p>{{ poi.znacka }}</p>
       {% endif %}
       
  {% endfor %}
  {% endif %}
 
  </div>
  </body>
</html>

zm/templates/misto.html
{% load static %}
{% load url from future %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
<!--   <link rel="stylesheet" type="text/css" href="http://petricko.cz/static/petricko/css/bootstrap-forms.css">-->
   
   <title>{{ poi }}</title>

   <script type="text/javascript" src="/static/js/jquery.tools.min.js"></script>
   <script type="text/javascript">
   function supports_html5_storage() {
  try {
    return 'localStorage' in window && window['localStorage'] !== null;
  } catch (e) {
    return false;
  }
}

    function saveLocalStorage () {
      var name = $('[name=name]').val();
      var email = $('[name=email]').val();
      if (supports_html5_storage())
      {
        localStorage.setItem("comment_name", name);
        localStorage.setItem("comment_email", email);
      }
    }

    function widgetIframe (w, h) {
      return "<iframe src=\"http://zelenamapa.cz/mapwidget/"+w+"x"+h+"/{{poi.pk}}/\" style=\"width:"+w+"px;height:"+h+"px;\" border=\"0\"></iframe>";
    }

  function generateWidgetIframe () {
      w = $('[name=widget_width]').val();
      h = $('[name=widget_height]').val();
      $('[name=widget_html_iframe]').val(widgetIframe(w, h));
    }

    $(document).ready(function () {
      if (supports_html5_storage())
      {
      $('[name=name]').val( localStorage.getItem("comment_name"));
      $('[name=email]').val( localStorage.getItem("comment_email"));
    }
    $("#wigdet_generator").hide();

        $("#togle_widget_generator").click(function(){
          $("#wigdet_generator").toggle();
        });
    })


   </script>

   <style type="text/css">
   .comment p, .comment h4 {margin: 1px 0 2px 0;}
   .comment {margin: 3px 0 10px 0;}
   </style>
  </head>
  <body>
  <div class="page" style="text-align:center;">
       <div class="content" style="max-width:500px; text-align:left;">

       <h2>{{ poi }}</h2>
       {% if poi.foto_thumb %}
            <a href="{{ MEDIA_URL }}{{ poi.foto_thumb }}"><img src="{{ MEDIA_URL }}{{ poi.foto_thumb }}" title="{{ poi }}" class="foto_thumb_misto"></a>
       {% else %}	    
            <div class="foto_thumb_misto"></div>
       {% endif %}


       <p class="poi_type"><img src="{{ poi.znacka.default_icon.url }}" title="{{ poi.znacka }}" class="poi_znacka"> {{ poi.znacka }}</p>


       <ul class="misto_vlastnosti">
       {% for vl in poi.vlastnosti.all %}
            {% if vl.status.show %}
            <li><img src="{{ vl.default_icon.url }}" title="{{ vl.nazev }}">{{  vl.nazev }}</li>
	    {% endif %}    
       {% endfor %}
       </ul>    
  
       {% if poi.address %}
       <p><span class="titulek">Adresa:</span><br>{{ poi.address|safe }}</p>
       {% endif %}
   
       {% if poi.url %}
       <p><span class="titulek">Webové stránky:</span><br><a href="{{ poi.url|safe }}" title="{{ poi.url|safe }}" target="_blank">{{ poi.url|safe }}</a></p>
       {% endif %}
   
       {% if poi.desc %}
       <p><span class="titulek">Popis:</span><br>{{ poi.desc|safe }}</p>
       {% endif %}
    
       {% if poi.desc_extra %}
       {{ poi.desc_extra|safe }}
       {% endif %}

       <p><a href="{% url 'mapa.views.addpoi_view' poi.id %}" title="Doplnit informace o objektu">upravit</a> |
       <a href="{% url 'mapa.views.mapa_view' poi.id %}" target="_top" title="Ukázat v mapě">zobrazit v mapě</a></p>
       
       </div>
       <div class="content" style="max-width:500px; text-align:left;clear:both;">
        <a href="https://twitter.com/share" class="twitter-share-button" data-via="zelenamapa" data-lang="en">Tweet</a>
      <div class="g-plus" data-action="share"></div>
      <div class="fb-like" data-href="http://zelenamapa.cz{{request.get_full_path}}" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-font="arial"></div>

<h3>Komentáře</h3>
<div class="addcoment">
<form method="post" class="form">
{% csrf_token %}
<div class="fieldWrapper">
<input type="text" id="id_name" name="name" maxlength="64" placeholder="Jméno" >
</div>
<div class="fieldWrapper">
  <input type="text" id="id_email" name="email" maxlength="64" placeholder="Email">
</div>
<div class="fieldWrapper">
<textarea id="id_content" rows="10" cols="40" name="content" placeholder="Komentář" style="width:500px;height:100px;"></textarea>
</div>
<br/>
<button onmousedown="saveLocalStorage();"><input type="submit"
value="Přidat" ></button>
</form>
{% for comment in comment_list %}
<div class="comment">
  <h4 style="display:inline-block;">{{comment.name}}</h4> <p style="display:inline-block;">{{comment.email}} | {{comment.created_at}}</p>
<p>{{comment.content|linebreaksbr}}</p>
</div>
{%endfor%}
</div>
<hr>

<a href="#" id="togle_widget_generator"><h4>HTML pro zobrazení odkazu na Zelenou mapu</h4></a>
       <div id="wigdet_generator">
       <p>Permalink na místo: <a href="http://zelenamapa.cz{% url 'mapa.views.mapa_view' poi.id %}" target="_top">http://zelenamapa.cz{% url 'mapa.views.mapa_view' poi.id %}</a></p>
       
       <p>Widgeta mapy - pro vložení do vlastních stránek.</p>
       
       <p>Velikost <input type="text" class="widget_input" name="widget_width" placeholder="šířka" onkeyup="generateWidgetIframe();" value="300"> x
       <input type="text" class="widget_input" name="widget_height" placeholder="výška" onkeyup="generateWidgetIframe();" value="300"></p>
       <textarea class="rounded_html_iframe"  name="widget_html_iframe" style="width:500px;"><iframe src="http://zelenamapa.cz/mapwidget/300x300/{{ poi.pk }}/" style="width:300px;height:300px;" border="0"></iframe></textarea>

       <p>Chcete-li odkázat na toto konkrétní místo v Zelené mapě, použijte následující HTML kód.</p>

       <p><a href="http://zelenamapa.cz{% url 'mapa.views.mapa_view' poi.id %}" target="_blank" style="float:left;"><img src="{% static "img/ikonka_zm100x100.jpg" %}"></a><br>
       <textarea rows="3" class="rounded_html_iframe" name="html" cols="40" style="width:290px;margin-left:20px;"><a href="http://zelenamapa.cz{% url 'mapa.views.mapa_view' poi.id %}"><img src="{% static "img/ikonka_zm100x100.jpg" %}" style="width:100px; height:100px;float:left;"></a></textarea>
       </p>
     </div>

</div>
</div>
       <!-- SOCIAL JS-->
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

      <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
      
      <!-- Place this tag where you want the share button to render. -->
      
      <!-- Place this tag after the last share tag. -->
      <script type="text/javascript">
        (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/plusone.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
      </script>
      <!-- END SOCIAL JS -->
  </body>
</html>

zm/templates/partner.html
<html>
  <head>
   <link rel="stylesheet" href="../media/css/zelenamapa.css" type="text/css" />
   
   <title>Partner mapy</title>
  </head>
  <body>
    <div class="page">
    <h3>Partner mapy</h3>


<p>Informace o partnerovi mapy...</p>


</div>

  </body>
</html>

zm/templates/static.html
{% load static %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
  {{ static.head  }}
  <title>{{ static.title }}</title>
  </head>
  <body class="static">
  <div class="content_left">
  {% if static.content %}
    {{ static.content|safe }}
  {% else %}	
    {{ static.short|safe }}
  {% endif %}
  </div>
  </body>
</html>

zm/templates/vlastnosti.html
{% load static %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
   
   <title>Vlastnosti</title>
  </head>
  <body>
  <div class="page" style="text-align:center;">
       <div class="content_left">

       {{ static_filtry.content|safe }}

       
       
       <dl class="desc_vlastnosti">
       {% for v in vlastnosti %}
       
       <dt><img src="{{v.default_icon.url}}"></img> <b>{{v.nazev}}</b>
       {% if not v.filtr  %}(Doplnkovy){% endif %}</dt>
       <dd>{{v.desc}}<dd>
       
       {% endfor %}
       </dl>
       
       </div>
</div>

  </body>
</html>

zm/templates/vrstvy.html
{% load static %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
   
   <title>Vrstvy</title>
  </head>
  <body>
  <div class="page" style="text-align:center;">
       <div class="content_left" >

       {{ static_vrstvy.content|safe }}

       <dl class="desc_vlastnosti">
       {% for v in vrstvy %}
       
       <dt><b>{{v.nazev}}</b></dt>
       <dd>{{v.desc|safe}}<dd>
       
       {% endfor %}
       </dl>
       
       

       </div>
</div>

  </body>
</html>

zm/templates/znacky.html
{% load static %}
<html>
  <head>
   <link rel="stylesheet" href="{% static "css/zelenamapa.css" %}" type="text/css" />
   
   <title>Znacky</title>
  </head>
  <body>
  <div class="page" style="text-align:center;">
       <div class="content_left" >

       {{ static_znacky.content|safe }}
       
       {% for v in vrstvy %}
        <h4>&nbsp;<br>{{ v }}:</h4>
	
        <dl class="desc_vlastnosti">
          {% for z in znacky %}
	     {% if z.vrstva = v  %}
	     <dt><img src="{{z.default_icon.url}}"></img> <b>{{z.nazev}}</b></dt>
	     <dd>{{z.desc|safe}}<dd>
	     {% endif %}
	  {% endfor %}
       
       </dl>
       {% endfor %}
       </div>
</div>

  </body>
</html>